version: "3.7"

services: 
    web:
        build:
            context: .
            dockerfile: compose/Dockerfile-Web
        expose:
            - 8000
        volumes:
            - ./src:/app
            - static_volume:/static
            - media_volume:/media
        env_file:
            - ./envs/web.dev
        depends_on: 
            - db

    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./envs/db.dev

    nginx:
        build:
            context: .
            dockerfile: compose/Dockerfile-Nginx
        volumes:
            - static_volume:/static
            - media_volume:/media
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - web

volumes:
    postgres_data:
    static_volume:
    media_volume:
