version: "3"

services: 
    web:
        build:
            context: .
            dockerfile: compose/Dockerfile
        ports: 
            - "8001:8001"
        volumes:
            - ./src:/app
        env_file:
            - ./envs/web.dev
        depends_on: 
            - db

    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./envs/db.dev

volumes:
    postgres_data: